# Generated by Django 5.1.4 on 2025-01-25 15:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genre", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
